version: '3.4'

services:
  demanda-service:
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "5148:5148"
    container_name: demanda-service
    volumes:
      - ./app:/app/app
    environment:
      - MODE=container 
      - ASPNETCORE_URLS=http://+:5148 
    env_file:
      - .env
    networks:
      - demanda-network 
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - demanda-network
    restart: unless-stopped
    
  pgadmin:
    container_name: demanda-pg-admin
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    volumes:
      - pg-admin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - demanda-network
networks:
  demanda-network:
    driver: bridge

volumes:
    postgres:
    pg-admin-volume:
